### ISSUE TITLE
Icons not coming out lilke they should

### ISSUE THREAD

**Issue by LauraPruett** [seiyria/gameicons-font#11]
I think you guys got some of the icon numbers and images wrong because they show up different on my webiste. ROFL and I need that power button one and it turns out to be angel wings and such.. ugh

**Comment by seiyria** [comment]
This is not a repo for the official gameicons. I just have a webfont generator that runs nightly. I recommend grabbing the icons you need and generating a custom font. It's a little obnoxious, but [here is an example repo of how to do it](https://github.com/IdleLands/gameicons-font/blob/master/.icon-map.js). It also lets you rename the icons as they come out.

I would need specifics icons to investigate further, but, if it appears correctly on [my site](https://seiyria.com/gameicons-font/), the resulting css/etc should be correct.
