### ISSUE TITLE
Adding own icons

### ISSUE THREAD

**Issue by yoruvo** [seiyria/gameicons-font#12]
Hi,

first off, thank you very much for this package, it's come really handy for prototyping a web game.

Is there an option to download the newest game-icons from the website, and merge them with a folder of custom icons? I would like to expand the font for my own game, with my own icons, while still using the regular game-icons.

I feel like I remember you mentioning something like that as a fork somewhere, and that you've already forked and done something like that yourself, but I wasn't successful in finding it.

Thanks!

**Comment by seiyria** [comment]
Yes, you can do this by using [`.icon-map.js`](https://github.com/IdleLands/gameicons-font/blob/master/.icon-map.js), forking this repo, and adding the different logic in that gulpfile. It's pretty inelegant, but it works. These days I [copy the icons](https://github.com/LandOfTheRair/Assets/tree/master/macicons) I need out and run a [different script](https://github.com/LandOfTheRair/LandOfTheRair/blob/master/client/scripts/prebuild-macicon-font.js) to format those icons as a webfont. I don't really rename them anymore unless needed.

Hope these two paths help you out!
