### ISSUE TITLE
Glyphs missing from the source site?

### ISSUE THREAD

**Issue by jugglervr** [seiyria/gameicons-font#13]
Hey there. I was wondering if you maintain a list of glyphs that haven't yet been converted from the source, and whether you had any tips for adding items and creating pull requests. (specifically there are some dice glyphs that I'd like to be able to use, but the completist in me enjoys the idea of helping this project to get to 100%)

**Comment by seiyria** [comment]
I do not maintain a list; everything should be updating nightly so if there's a glyph you don't see, it should be present within 24 hours. If there are some things missing, then it's likely gameicons doesn't have them added in the zip [I grab from here](https://github.com/seiyria/gameicons-font/blob/master/gulpfile.js#L15). 

I'll close this for now, but feel free to keep the conversation open if you figure out why they're missing, and if you have a list already that I can check, that'd be great too.

**Comment by jugglervr** [comment]
Oh, ok. I'm planning to grab the icon descriptions to use as part of a search project. I'll let you know what I find in the next few weeks.

**Comment by jugglervr** [comment]
Alright, it looks like nothing was missing (NICE completeness!), but some inconsistent glyph IDs from the source result in weird search behavior. For example, the ID for a d8 is "dice-eight-faces-eight" but the ID for a d4 is "d4" so a d4 never shows up in a search for "dice" and a d8 never shows up in a search for, well, "d8". ;D

The source site gets around this by also searching the data and a (inconsistent) description field. I ended up scraping all that data down from their API while I was investigating. If you're interested in leveraging the tags for additional search granularity, I made a gist: https://gist.github.com/jugglervr/2071db9405f948b4e2dd881af7cb7f1d

**Comment by seiyria** [comment]
Awesome, glad to hear it! I'm not opposed to it but I don't think I would end up adding it myself; I think anyone who needs it would go to game-icons.net to search for what they need first, then download from here/set their glyph as needed.
