### ISSUE TITLE
Font included in my rpg-cards fork

### ISSUE THREAD

**Issue by mephitrpg** [seiyria/gameicons-font#15]
Hi,

thank you for this font! I hope you'll continue to update it!

I included it into my fork of the rpg-cards repository and created a new <icon> custom HTML tag that uses it.

https://github.com/mephitrpg/rpg-cards

**Comment by seiyria** [comment]
Hey, this is really cool! It reminds me a bit of https://deck.zone :D Thanks for using the project! It updates every night, so it'll be updated any time they update their font!

**Comment by giorgiobeggiora** [comment]
I see that the CSS file is not updated every night, does it update only if necessary?

**Comment by seiyria** [comment]
It updates any time there's new icons.
