### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by filipkappa** [seiyria/gameicons-font#17]
I included the following link in my HTML file.
`<link href="css/game-icons.css" rel="stylesheet">`

And included the icon tag with the proper class:
`<i class="game-icon game-icon-anchor">`

just like in the readme - and I see nothing.

**Comment by seiyria** [comment]
without a minimal reproduction I can't help you. I recommend looking at the example [here](https://github.com/seiyria/gameicons-font/tree/master/test) and seeing what's different with your test.

**Comment by filipkappa** [comment]
Well, you're not really using any <i> tags in the HTML page there.

I've tried this, with the exact same setup downloaded from here - it doesn't work.
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link href="css/game-icons.css" rel="stylesheet">
    <link href="css/app.css" rel="stylesheet">
    <title>Game Icons Font</title>
</head>
<body>

<!--Here is the icon-->
<i class="game-icon game-icon-anchor">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/mithril/0.2.3/mithril.min.js"></script>
    <script src="./js/app.js"></script>
</body>
</html>
```

**Comment by seiyria** [comment]
As stated if you have no minimal reproduction there's nothing I can help with. It works on my site but I can't see why it wouldn't work for you
