### ISSUE TITLE
Stability of numbered glyphs

### ISSUE THREAD

**Issue by oganm** [seiyria/gameicons-font#7]
I just noticed for icons of the same name but from different authors are named here as [icon name], [icon name]-2 (example clover (by Sbed), clover-2 (by Lorc)). I was wondering if there was a mechanism in place to ensure that updates does not change which icon is assigned to which glyph in the fonts here, or if addition of a new icon with the same name can cause the old icon to be named [icon name]-2.

**Comment by seiyria** [comment]
Regrettably there is not, I didn't really consider this when I made the mechanism: https://github.com/seiyria/gameicons-font/blob/master/gulpfile.js#L29-L39

It's very simplistic.

**Comment by oganm** [comment]
excuse my lack of javascript knowledge but is there a logical way they are ordered then? I was hoping that they'd be alphabetic by default but they don't appear to be. Can I infer authorship without manually checking the icons if I know who the possible authors are?

**Comment by seiyria** [comment]
You're fine. Basically, it's the order they appear in the [zip file](http://game-icons.net/archives/svg/zip/000000/transparent/game-icons.net.svg.zip). 

So, they're ordered basically by author, alphabetically.

**Comment by oganm** [comment]
Hmm that's weird. because clover is sbed, clover-2 is lorc, so seems to be reverse alphabetical, but then rss is Delapouite while rss-2 is Lorc, which was why I got confused. They are also ordered this way in the zip file as far as I can see

**Comment by seiyria** [comment]
It's really hard to say, sorry. I set this up and let it run nightly basically, I don't maintain it anymore.

**Comment by oganm** [comment]
don't worry about it. thanks!

**Comment by oganm** [comment]
It seems the files are sorted by creation or modification time, which incidentally would make sure that old icon ids to be preserved unless that record is lost

**Comment by seiyria** [comment]
Excellent! That seems pretty solid then. I'm going to close this issue since it seems to be what you were going for, but let me know if there's anything else! 🎉
